image: node:8-alpine

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
  - npm install

cache:
  paths:
    - node_modules/

publish:
  stage: deploy
  only:
    - tags
  script:
    - npm publish --access=restricted